### ISSUE TITLE
Missing libgdal.so.32

### ISSUE THREAD

**Issue by void-rooster** [gis-ops/docker-valhalla#148]
Got an error building the latest image:

```
 => CACHED [valhalla internal] load git source https://github.com/gis-ops/docker-valhalla.git                                  0.2s
 => [valhalla internal] load metadata for docker.io/library/ubuntu:23.04                                                       0.1s
 => [valhalla internal] load metadata for ghcr.io/valhalla/valhalla:latest                                                     0.2s
 => [valhalla runner_base 1/8] FROM docker.io/library/ubuntu:23.04@sha256:5a828e28de105c3d7821c4442f0f5d1c52dc16acf4999d5f31a  0.0s 
 => [valhalla builder 1/2] FROM ghcr.io/valhalla/valhalla:latest@sha256:9d5c6ce5108fbf4346d0bc11786590d1c93aa23b7217f286e0e3e  0.0s
 => CACHED [valhalla runner_base 2/8] RUN apt-get update > /dev/null &&   export DEBIAN_FRONTEND=noninteractive &&   apt-get   0.0s
 => CACHED [valhalla builder 2/2] RUN cd /usr/local/bin &&   preserve="valhalla_service valhalla_build_tiles valhalla_build_c  0.0s
 => CACHED [valhalla runner_base 3/8] COPY --from=builder /usr/local /usr/local                                                0.0s
 => CACHED [valhalla runner_base 4/8] COPY --from=builder /usr/lib/python3/dist-packages/valhalla/* /usr/lib/python3/dist-pac  0.0s
 => CACHED [valhalla runner_base 5/8] RUN groupadd -g 1001 valhalla &&   useradd -lmu 1001 -g valhalla valhalla &&   mkdir /c  0.0s
 => CACHED [valhalla runner_base 6/8] COPY scripts/. /valhalla/scripts                                                         0.0s
 => CACHED [valhalla runner_base 7/8] WORKDIR /custom_files                                                                    0.0s
 => ERROR [valhalla runner_base 8/8] RUN python -c "import valhalla,sys; print (sys.version, valhalla)"   && valhalla_build_c  0.2s
------                                                                                                                              
 > [valhalla runner_base 8/8] RUN python -c "import valhalla,sys; print (sys.version, valhalla)"   && valhalla_build_config | jq type   && cat /usr/local/src/valhalla_version   && valhalla_build_tiles -v   && ls -la /usr/local/bin/valhalla*:                       
0.182 Traceback (most recent call last):                                                                                            
0.182   File "<string>", line 1, in <module>                                                                                        
0.182   File "/usr/lib/python3/dist-packages/valhalla/__init__.py", line 2, in <module>
0.182     from .python_valhalla import *
0.182 ImportError: libgdal.so.32: cannot open shared object file: No such file or directory
------
failed to solve: process "/bin/sh -c python -c \"import valhalla,sys; print (sys.version, valhalla)\"   && valhalla_build_config | jq type   && cat /usr/local/src/valhalla_version   && valhalla_build_tiles -v   && ls -la /usr/local/bin/valhalla*" did not complete successfully: exit code: 1
```

**Comment by nilsnolde** [comment]
Try again on Monday: https://github.com/valhalla/valhalla/pull/4629

**Comment by nilsnolde** [comment]
Sorry, I just realized the `latest` cron job failed a few hours ago. I just pushed a fix, it was indeed a problem with this image too..
